# Generated by Django 4.1.1 on 2022-11-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horquillas', '0002_clientes_inicio_maquina_delete_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='fecha',
            field=models.CharField(max_length=100),
        ),
    ]
